services:
  llm:
    build: 
      context: ./llm
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - EXPLORER_API_KEY=${EXPLORER_API_KEY}
      - BASE_URL=${BASE_URL}
      - BOT_TOKEN=${BOT_TOKEN_DEV} # Ensure BOT_TOKEN is included
    volumes:
      - ./llm:/app

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN_DEV}
      - GROUP_CHAT_ID=${GROUP_CHAT_ID_DEV}
      - REDIS_HOST=${REDIS_HOST_DEV}
      - REDIS_PORT=${REDIS_PORT_DEV}
      - REDIS_PASSWORD=${REDIS_PASSWORD_DEV}
      - REDIS_USERNAME=${REDIS_USERNAME_DEV}
      - LLM_URL=${LLM_URL_DEV}
    volumes:
      - ./bot:/app
    depends_on:
      - redis # Ensure Redis starts before the bot

  redis:
     image: "redis:latest"
     networks:
       - app-network
     ports:
       - "6379:6379"

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: