/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HowtouseImport } from './routes/howtouse'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const HowtouseRoute = HowtouseImport.update({
  id: '/howtouse',
  path: '/howtouse',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/howtouse': {
      id: '/howtouse'
      path: '/howtouse'
      fullPath: '/howtouse'
      preLoaderRoute: typeof HowtouseImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/howtouse': typeof HowtouseRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/howtouse': typeof HowtouseRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/howtouse': typeof HowtouseRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/howtouse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/howtouse'
  id: '__root__' | '/' | '/howtouse'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowtouseRoute: typeof HowtouseRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowtouseRoute: HowtouseRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/howtouse"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/howtouse": {
      "filePath": "howtouse.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
