version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      # For development: mount the source code
      - .:/app
      # Don't overwrite node_modules
      - /app/node_modules
    restart: unless-stopped